name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Compile Java files
      - name: Compile Java Files
        run: |
          mkdir -p bin
          javac -d bin src/main/java/com/example/Calculator.java src/test/java/com/example/CalculatorTest.java

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          java -jar junit-platform-console-standalone-1.9.2.jar \
            --class-path bin \
            --scan-class-path
