name: Java CI Workflow

# Events that trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    # The environment where the workflow runs
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Use the required JDK version
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies and build the project
      - name: Build with Maven
        run: mvn clean compile

      # Step 5: Run the tests
      - name: Run Tests
        run: mvn test
